### ISSUE TITLE
Turning this into GitHub Pages

### ISSUE THREAD

**Issue by ACMCMC** [rainbowbreeze/ai_for_community_events#1]
Hi! I loved this idea :) What do you say if we turn this into a GitHub pages website to make it easier to access?

**Comment by ACMCMC** [comment]
(I can take care of that - should be quick!)

**Comment by rainbowbreeze** [comment]
Great idea, and just done - https://rainbowbreeze.github.io/ai_for_community_events/

WDYT?

**Comment by ACMCMC** [comment]
Yep, looks great, thanks a lot! :)
